name: IP Extractor

# 触发条件，每12小时执行一次
on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时执行一次，使用 UTC 时间

  # 手动触发工作流按钮
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run_script:
    runs-on: ubuntu-latest  # 在 Ubuntu 环境下运行

    steps:
      # 步骤 1：检出代码
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 步骤 2：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 设置 Python 版本为 3.9

      # 步骤 3：安装依赖项
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装 requirements.txt 中列出的所有依赖项

      # 步骤 4：运行 Python 脚本
      - name: Run IP extraction script
        run: python ip_extractor.py  # 运行你的 Python 脚本
