name: IP Extractor

on:
  schedule:
    # 每12小时执行一次
    - cron: '0 */12 * * *'
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 可以选择其他版本

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 手动安装 ChromeDriver
      - name: Install ChromeDriver
        run: |
          # 安装依赖包
          sudo apt-get update
          sudo apt-get install -y wget unzip

          # 下载 ChromeDriver 并解压
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip -O /tmp/chromedriver.zip
          unzip /tmp/chromedriver.zip -d /tmp/
          sudo mv /tmp/chromedriver /usr/local/bin/

          # 确保它可执行
          sudo chmod +x /usr/local/bin/chromedriver

      # 配置 Git 用户信息
      - name: Configure Git
        run: |
          git config --global user.email "5981174@qq.com"
          git config --global user.name "xgonce"

      # 运行 IP 提取脚本
      - name: Run IP extraction script
        run: python ip_extractor.py

      # 提交并推送生成的文件
      - name: Commit and push the generated files
        run: |
          git add ip.txt ip_with_country.txt
          git commit -m "Add generated IP files"
          git push https://xgonce:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/xgonce/myip.git
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
