name: IP Extractor

on:
  schedule:
    # 每12小时执行一次
    - cron: '0 */12 * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 可以选择其他版本

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行 IP 提取脚本
      - name: Run IP extraction script
        run: python ip_extractor.py
