name: IP Extractor

on:
  schedule:
    - cron: '0 */2 * * *'  # 每2小时执行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 手动安装 ChromeDriver
      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip -O /tmp/chromedriver.zip
          unzip /tmp/chromedriver.zip -d /tmp/
          sudo mv /tmp/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      # 配置 Git 用户信息
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      # 运行 IP 提取脚本
      - name: Run IP extraction script
        run: python ip_extractor.py

      # 提交并推送生成的文件
      - name: Commit and push the generated files
        run: |
          git add ip.txt ip_with_country.txt
          git commit -m "Add generated IP files"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/madison80309/myip.git
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
